# Form implementation generated from reading ui file 'ui/addstandsdialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddStandsDialog(object):
    def setupUi(self, AddStandsDialog):
        AddStandsDialog.setObjectName("AddStandsDialog")
        AddStandsDialog.resize(691, 446)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(AddStandsDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(AddStandsDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.template_cb = QtWidgets.QComboBox(AddStandsDialog)
        self.template_cb.setObjectName("template_cb")
        self.verticalLayout.addWidget(self.template_cb)
        self.label_2 = QtWidgets.QLabel(AddStandsDialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.stands_te = QtWidgets.QTextEdit(AddStandsDialog)
        self.stands_te.setObjectName("stands_te")
        self.verticalLayout.addWidget(self.stands_te)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(AddStandsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        self.add_btn = QtWidgets.QPushButton(AddStandsDialog)
        self.add_btn.setEnabled(False)
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout.addWidget(self.add_btn)
        self.cancel_btn = QtWidgets.QPushButton(AddStandsDialog)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout.addWidget(self.cancel_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(AddStandsDialog)
        QtCore.QMetaObject.connectSlotsByName(AddStandsDialog)

    def retranslateUi(self, AddStandsDialog):
        _translate = QtCore.QCoreApplication.translate
        AddStandsDialog.setWindowTitle(_translate("AddStandsDialog", "Form"))
        self.label.setText(_translate("AddStandsDialog", "Template"))
        self.label_2.setText(_translate("AddStandsDialog", "Cameras (SN:IP)"))
        self.add_btn.setText(_translate("AddStandsDialog", "Add"))
        self.cancel_btn.setText(_translate("AddStandsDialog", "Cancel"))
