# Form implementation generated from reading ui file 'ui/managewindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ManageWindow(object):
    def setupUi(self, ManageWindow):
        ManageWindow.setObjectName("ManageWindow")
        ManageWindow.resize(796, 469)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ManageWindow)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.stands_tab = QtWidgets.QTabWidget(ManageWindow)
        self.stands_tab.setObjectName("stands_tab")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.templates_list = QtWidgets.QListWidget(self.tab)
        self.templates_list.setObjectName("templates_list")
        self.verticalLayout_4.addWidget(self.templates_list)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        self.add_template_btn = QtWidgets.QPushButton(self.tab)
        self.add_template_btn.setObjectName("add_template_btn")
        self.horizontalLayout.addWidget(self.add_template_btn)
        self.remove_template_btn = QtWidgets.QPushButton(self.tab)
        self.remove_template_btn.setObjectName("remove_template_btn")
        self.horizontalLayout.addWidget(self.remove_template_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.stands_tab.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stands_list = QtWidgets.QListWidget(self.tab_2)
        self.stands_list.setObjectName("stands_list")
        self.verticalLayout_5.addWidget(self.stands_list)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.add_stands_btn = QtWidgets.QPushButton(self.tab_2)
        self.add_stands_btn.setObjectName("add_stands_btn")
        self.horizontalLayout_2.addWidget(self.add_stands_btn)
        self.remove_stands_btn = QtWidgets.QPushButton(self.tab_2)
        self.remove_stands_btn.setObjectName("remove_stands_btn")
        self.horizontalLayout_2.addWidget(self.remove_stands_btn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.stands_tab.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.stands_tab)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(ManageWindow)
        self.stands_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ManageWindow)

    def retranslateUi(self, ManageWindow):
        _translate = QtCore.QCoreApplication.translate
        ManageWindow.setWindowTitle(_translate("ManageWindow", "Form"))
        self.add_template_btn.setText(_translate("ManageWindow", "Add"))
        self.remove_template_btn.setText(_translate("ManageWindow", "Remove"))
        self.stands_tab.setTabText(self.stands_tab.indexOf(self.tab), _translate("ManageWindow", "Templates"))
        self.add_stands_btn.setText(_translate("ManageWindow", "Add"))
        self.remove_stands_btn.setText(_translate("ManageWindow", "Remove"))
        self.stands_tab.setTabText(self.stands_tab.indexOf(self.tab_2), _translate("ManageWindow", "Stands"))
